package entidades;

import java.math.BigDecimal;

/**
 * Canal generated by hbm2java
 */

public class Canal{


    // Fields    

     private BigDecimal id;
     private String descricao;

    // Constructors

    /** default constructor */
    public Canal() {
    }

    public Canal(BigDecimal id, String descriao) {
        this.id = id;
        this.descricao = descriao;
    }
    
    public Canal(String descriao) {
        this.descricao = descriao;
    }
    
    // Property accessors

    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getDescriao() {
        return this.descricao;
    }
    
    public void setDescriao(String descriao) {
        this.descricao = descriao;
    }

    
    //TODO GAMBIARRAS
	public Object getDescricao() {
		return getDescriao();
	}
	public void setDescricao(String descricao) {
		setDescriao(descricao);
	}

	@Override
	public String toString() {
		return "Canal [id=" + id + ", descricao=" + descricao + "]";
	}


}
