package entidades;
import java.math.BigDecimal;


/**
 * Continente generated by hbm2java
 */

public class Continente{


    // Fields    

     private BigDecimal id;
     private String nome;
     private String sigla;


    // Constructors

    /** default constructor */
    public Continente() {
    }
    
    /** full constructor */
    public Continente(BigDecimal id, String nome, String sigla) {
        this.id = id;
        this.nome = nome;
        this.sigla = sigla;
    }
    
    public Continente(String nome, String sigla) {
        this.nome = nome;
        this.sigla = sigla;
    }
    
    @Override
    public String toString() {
    	return "Continente [id=" + id + ", nome=" + nome + ", sigla="
    			+ sigla + "]";
    }
   
    // Property accessors


	public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    
    public void insert()
	{
		
	}
	
	public void delete()
	{
		
	}
	
	public void update()
	{
		
	}

}
