package entidades;




/**
 * MarcaCanalId generated by hbm2java
 */

public class MarcaCanal  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String formaAcesso;
     private String observacoes;
     private Marca marca;
     private Canal canal;
     private String abrangencia;


    // Constructors

    /** default constructor */
    public MarcaCanal() {
    }

	/** minimal constructor */
    public MarcaCanal(Marca marca, Canal canal) {
        this.marca = marca;
        this.canal = canal;
    }
    
    /** full constructor */
    public MarcaCanal(String formaAcesso, String observacoes, Marca marca, Canal canal, String abrangencia) {
        this.formaAcesso = formaAcesso;
        this.observacoes = observacoes;
        this.marca = marca;
        this.canal = canal;
        this.abrangencia = abrangencia;
    }
    

   
    // Property accessors

    public String getFormaAcesso() {
        return this.formaAcesso;
    }
    
    public void setFormaAcesso(String formaAcesso) {
        this.formaAcesso = formaAcesso;
    }

    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    public Canal getCanal() {
        return this.canal;
    }
    
    public void setCanal(Canal canal) {
        this.canal = canal;
    }

    public String getAbrangencia() {
        return this.abrangencia;
    }
    
    public void setAbrangencia(String abrangencia) {
        this.abrangencia = abrangencia;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MarcaCanal) ) return false;
		 MarcaCanal castOther = ( MarcaCanal ) other; 
         
		 return ( (this.getFormaAcesso()==castOther.getFormaAcesso()) || ( this.getFormaAcesso()!=null && castOther.getFormaAcesso()!=null && this.getFormaAcesso().equals(castOther.getFormaAcesso()) ) )
 && ( (this.getObservacoes()==castOther.getObservacoes()) || ( this.getObservacoes()!=null && castOther.getObservacoes()!=null && this.getObservacoes().equals(castOther.getObservacoes()) ) )
 && ( (this.getMarca()==castOther.getMarca()) || ( this.getMarca()!=null && castOther.getMarca()!=null && this.getMarca().equals(castOther.getMarca()) ) )
 && ( (this.getCanal()==castOther.getCanal()) || ( this.getCanal()!=null && castOther.getCanal()!=null && this.getCanal().equals(castOther.getCanal()) ) )
 && ( (this.getAbrangencia()==castOther.getAbrangencia()) || ( this.getAbrangencia()!=null && castOther.getAbrangencia()!=null && this.getAbrangencia().equals(castOther.getAbrangencia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFormaAcesso() == null ? 0 : this.getFormaAcesso().hashCode() );
         result = 37 * result + ( getObservacoes() == null ? 0 : this.getObservacoes().hashCode() );
         result = 37 * result + ( getMarca() == null ? 0 : this.getMarca().hashCode() );
         result = 37 * result + ( getCanal() == null ? 0 : this.getCanal().hashCode() );
         result = 37 * result + ( getAbrangencia() == null ? 0 : this.getAbrangencia().hashCode() );
         return result;
   }

@Override
public String toString() {
	return "MarcaCanal [formaAcesso=" + formaAcesso + ", observacoes="
			+ observacoes + ", marca=" + marca + ", canal=" + canal
			+ ", abrangencia=" + abrangencia + "]";
}   





}
