package entidades;

import java.math.BigDecimal;


/**
 * Modelagem generated by hbm2java
 */

public class Modelagem  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
     private String nome;
     private String status;
     private String genero;
     private String descricao;
     private String codigoInternoIndustria;


    // Constructors

    /** default constructor */
    public Modelagem() {
    }
    
    /** full constructor */
    public Modelagem(BigDecimal id, String nome, String status, String genero, String descricao, String codigoInternoIndustria) {
        this.id = id;
        this.nome = nome;
        this.status = status;
        this.genero = genero;
        this.descricao = descricao;
        this.codigoInternoIndustria = codigoInternoIndustria;
    }
    

   
    // Property accessors

    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getCodigoInternoIndustria() {
        return this.codigoInternoIndustria;
    }
    
    public void setCodigoInternoIndustria(String codigoInternoIndustria) {
        this.codigoInternoIndustria = codigoInternoIndustria;
    }

	@Override
	public String toString() {
		return "Modelagem [id=" + id + ", nome=" + nome + ", status=" + status
				+ ", genero=" + genero + ", descricao=" + descricao
				+ ", codigoInternoIndustria=" + codigoInternoIndustria + "]";
	}

}
