package entidades;


/**
 * ModelagemMarcaId generated by hbm2java
 */

public class ModelagemMarca  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Modelagem modelagem;
     private Marca marca;


    // Constructors

    /** default constructor */
    public ModelagemMarca() {
    }

    
    /** full constructor */
    public ModelagemMarca(Modelagem modelagem, Marca marca) {
        this.modelagem = modelagem;
        this.marca = marca;
    }
    

   
    // Property accessors

    public Modelagem getModelagem() {
        return this.modelagem;
    }
    
    public void setModelagem(Modelagem modelagem) {
        this.modelagem = modelagem;
    }

    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelagemMarca) ) return false;
		 ModelagemMarca castOther = ( ModelagemMarca ) other; 
         
		 return ( (this.getModelagem()==castOther.getModelagem()) || ( this.getModelagem()!=null && castOther.getModelagem()!=null && this.getModelagem().equals(castOther.getModelagem()) ) )
 && ( (this.getMarca()==castOther.getMarca()) || ( this.getMarca()!=null && castOther.getMarca()!=null && this.getMarca().equals(castOther.getMarca()) ) );
   }


@Override
public String toString() {
	return "ModelagemMarca [modelagem=" + modelagem + ", marca=" + marca + "]";
}
   
}
