package entidades;
import java.math.BigDecimal;


/**
 * ModelagemDadosTamanhoId generated by hbm2java
 */

public class ModelagemDadosTamanho {


    // Fields    

     private double valorMedidaInicial;
     private Modelagem modelagem;
     private TamanhoTipoGrade tamanhoTipoGrade;
     private BigDecimal padraoMedidaId;
     private TipoMedida tipoMedida;
     private Double valorMedidaFinal;


    // Constructors

    /** default constructor */
    public ModelagemDadosTamanho() {
    }

	/** minimal constructor */
    public ModelagemDadosTamanho(double valorMedidaInicial, Modelagem modelagem, TamanhoTipoGrade tamanhoTipoGrade, BigDecimal padraoMedidaId, TipoMedida tipoMedida) {
        this.valorMedidaInicial = valorMedidaInicial;
        this.modelagem = modelagem;
        this.tamanhoTipoGrade = tamanhoTipoGrade;
        this.padraoMedidaId = padraoMedidaId;
        this.tipoMedida = tipoMedida;
    }
    
    /** full constructor */
    public ModelagemDadosTamanho(double valorMedidaInicial, Modelagem modelagem, TamanhoTipoGrade tamanhoTipoGrade, BigDecimal padraoMedidaId, TipoMedida tipoMedida, Double valorMedidaFinal) {
        this.valorMedidaInicial = valorMedidaInicial;
        this.modelagem = modelagem;
        this.tamanhoTipoGrade = tamanhoTipoGrade;
        this.padraoMedidaId = padraoMedidaId;
        this.tipoMedida = tipoMedida;
        this.valorMedidaFinal = valorMedidaFinal;
    }
    

   
    // Property accessors

    public double getValorMedidaInicial() {
        return this.valorMedidaInicial;
    }
    
    public void setValorMedidaInicial(double valorMedidaInicial) {
        this.valorMedidaInicial = valorMedidaInicial;
    }

    public Modelagem getModelagem() {
        return this.modelagem;
    }
    
    public void setModelagem(Modelagem modelagem) {
        this.modelagem = modelagem;
    }

    public TamanhoTipoGrade getTamanhoTipoGrade() {
        return this.tamanhoTipoGrade;
    }
    
    public void setTamanhoTipoGrade(TamanhoTipoGrade tamanhoTipoGrade) {
        this.tamanhoTipoGrade = tamanhoTipoGrade;
    }

    public BigDecimal getPadraoMedidaId() {
        return this.padraoMedidaId;
    }
    
    public void setPadraoMedidaId(BigDecimal padraoMedidaId) {
        this.padraoMedidaId = padraoMedidaId;
    }

    public TipoMedida getTipoMedida() {
        return this.tipoMedida;
    }
    
    public void setTipoMedida(TipoMedida tipoMedida) {
        this.tipoMedida = tipoMedida;
    }

    public Double getValorMedidaFinal() {
        return this.valorMedidaFinal;
    }
    
    public void setValorMedidaFinal(Double valorMedidaFinal) {
        this.valorMedidaFinal = valorMedidaFinal;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelagemDadosTamanho) ) return false;
		 ModelagemDadosTamanho castOther = ( ModelagemDadosTamanho ) other; 
         
		 return (this.getValorMedidaInicial()==castOther.getValorMedidaInicial())
 && ( (this.getModelagem()==castOther.getModelagem()) || ( this.getModelagem()!=null && castOther.getModelagem()!=null && this.getModelagem().equals(castOther.getModelagem()) ) )
 && ( (this.getTamanhoTipoGrade()==castOther.getTamanhoTipoGrade()) || ( this.getTamanhoTipoGrade()!=null && castOther.getTamanhoTipoGrade()!=null && this.getTamanhoTipoGrade().equals(castOther.getTamanhoTipoGrade()) ) )
 && ( (this.getPadraoMedidaId()==castOther.getPadraoMedidaId()) || ( this.getPadraoMedidaId()!=null && castOther.getPadraoMedidaId()!=null && this.getPadraoMedidaId().equals(castOther.getPadraoMedidaId()) ) )
 && ( (this.getTipoMedida()==castOther.getTipoMedida()) || ( this.getTipoMedida()!=null && castOther.getTipoMedida()!=null && this.getTipoMedida().equals(castOther.getTipoMedida()) ) )
 && ( (this.getValorMedidaFinal()==castOther.getValorMedidaFinal()) || ( this.getValorMedidaFinal()!=null && castOther.getValorMedidaFinal()!=null && this.getValorMedidaFinal().equals(castOther.getValorMedidaFinal()) ) );
   }

@Override
public String toString() {
	return "ModelagemDadosTamanho [valorMedidaInicial=" + valorMedidaInicial
			+ ", modelagem=" + modelagem + ", tamanhoTipoGrade="
			+ tamanhoTipoGrade + ", padraoMedidaId=" + padraoMedidaId
			+ ", tipoMedida=" + tipoMedida + ", valorMedidaFinal="
			+ valorMedidaFinal + "]";
}
  

}
