package entidades;

import java.math.BigDecimal;


/**
 * PadraoMedida generated by hbm2java
 */

public class PadraoMedida {


    // Fields    

     private BigDecimal id;
     private String descricao;


    // Constructors

    /** default constructor */
    public PadraoMedida() {
    }

	/** minimal constructor */
    public PadraoMedida(BigDecimal id) {
        this.id = id;
    }
    
    /** full constructor */
    public PadraoMedida(BigDecimal id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    

    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

	@Override
	public String toString() {
		return "PadraoMedida [id=" + id + ", descricao=" + descricao + "]";
	}
}
