package entidades;
import java.math.BigDecimal;


/**
 * Pais generated by hbm2java
 */

public class Pais  implements java.io.Serializable {


	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private Continente continente;
	private String nome;
	private String sigla;
	private String nacionalidade;

	// Constructors

	/** default constructor */
	public Pais() {
	}

	/** full constructor */
	public Pais(BigDecimal id, Continente continente, String nome, String sigla, String nacionalidade) {
		this.id = id;
		this.continente = continente;
		this.nome = nome;
		this.sigla = sigla;
		this.nacionalidade = nacionalidade;
	}

	public Pais(Continente continente, String nome, String sigla, String nacionalidade) {
		this.continente = continente;
		this.nome = nome;
		this.sigla = sigla;
		this.nacionalidade = nacionalidade;
	}

	// Property accessors

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal idContinente) {
		this.id = idContinente;
	}

	public Continente getContinente() {
		return this.continente;
	}

	public void setContinente(Continente continente) {
		this.continente = continente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	public String getNacionalidade() {
		return this.nacionalidade;
	}

	public void setNacionalidade(String nacionalidade) {
		this.nacionalidade = nacionalidade;
	}

	@Override
	public String toString() {
		return "Pais [id=" + id + ", continente=" + continente + ", nome="
				+ nome + ", sigla=" + sigla + ", nacionalidade="
				+ nacionalidade + "]";
	}
}
