package entidades;
import java.math.BigDecimal;


/**
 * TamanhoTipoGrade generated by hbm2java
 */

public class TamanhoTipoGrade{


    // Fields    

     private BigDecimal id;
     private TipoGrade tipoGrade;
     private String descricao;


    // Constructors

    /** default constructor */
    public TamanhoTipoGrade() {
    }

	/** minimal constructor */
    public TamanhoTipoGrade(BigDecimal id, TipoGrade tipoGrade, String descricao) {
        this.id = id;
        this.tipoGrade = tipoGrade;
        this.descricao = descricao;
    }
    

    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    public TipoGrade getTipoGrade() {
        return this.tipoGrade;
    }
    
    public void setTipoGrade(TipoGrade tipoGrade) {
        this.tipoGrade = tipoGrade;
    }

    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

	@Override
	public String toString() {
		return "TamanhoTipoGrade [id=" + id + ", tipoGrade=" + tipoGrade
				+ ", descricao=" + descricao + "]";
	}

}
