package entidades;
import java.math.BigDecimal;


/**
 * TipoGrade generated by hbm2java
 */

public class TipoGrade{


    // Fields    

     private BigDecimal id;
     private String descricao;


    // Constructors

    /** default constructor */
    public TipoGrade() {
    }
    
    /** full constructor */
    public TipoGrade(BigDecimal id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    

   
    // Property accessors

    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

	@Override
	public String toString() {
		return "TipoGrade [id=" + id + ", descricao=" + descricao + "]";
	}

}
