package entidades;
// Generated 11/09/2014 22:22:12 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Marca generated by hbm2java
 */

public class Marca  implements java.io.Serializable {


    // Fields    

     private long codigo;
     private String nome;
     private String descricao;
     private String logomarca;
     private Date dataCriacao;
     private char genero;
     private short idadeInicial;
     private short idadeFinal;
     private char status;


    // Constructors

    /** default constructor */
    public Marca() {
    }

	/** minimal constructor */
    public Marca(long codigo, String nome, Date dataCriacao, char genero, short idadeInicial, short idadeFinal, char status) {
        this.codigo = codigo;
        this.nome = nome;
        this.dataCriacao = dataCriacao;
        this.genero = genero;
        this.idadeInicial = idadeInicial;
        this.idadeFinal = idadeFinal;
        this.status = status;
    }
      
    // Property accessors

    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getLogomarca() {
        return this.logomarca;
    }
    
    public void setLogomarca(String logomarca) {
        this.logomarca = logomarca;
    }

    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    public char getGenero() {
        return this.genero;
    }
    
    public void setGenero(char genero) {
        this.genero = genero;
    }

    public short getIdadeInicial() {
        return this.idadeInicial;
    }
    
    public void setIdadeInicial(short idadeInicial) {
        this.idadeInicial = idadeInicial;
    }

    public short getIdadeFinal() {
        return this.idadeFinal;
    }
    
    public void setIdadeFinal(short idadeFinal) {
        this.idadeFinal = idadeFinal;
    }

    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }


}
