package entidades;

import java.math.BigDecimal;


/**
 * PadraoMedida generated by hbm2java
 */

public class PadraoMedida {


    // Fields    

     private BigDecimal codigo;
     private String descricao;


    // Constructors

    /** default constructor */
    public PadraoMedida() {
    }

	/** minimal constructor */
    public PadraoMedida(BigDecimal codigo) {
        this.codigo = codigo;
    }
    
    /** full constructor */
    public PadraoMedida(BigDecimal codigo, String descricao) {
        this.codigo = codigo;
        this.descricao = descricao;
    }
    

    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
}
