package entidades;


/**
 * PaisMarcaId generated by hbm2java
 */

public class PaisMarca{


    // Fields    

     private Marca marca;
     private Pais pais;


    // Constructors

    /** default constructor */
    public PaisMarca() {
    }

    
    /** full constructor */
    public PaisMarca(Marca marca, Pais pais) {
        this.marca = marca;
        this.pais = pais;
    }
    

   
    // Property accessors

    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaisMarca) ) return false;
		 PaisMarca castOther = ( PaisMarca ) other; 
         
		 return ( (this.getMarca()==castOther.getMarca()) || ( this.getMarca()!=null && castOther.getMarca()!=null && this.getMarca().equals(castOther.getMarca()) ) )
 && ( (this.getPais()==castOther.getPais()) || ( this.getPais()!=null && castOther.getPais()!=null && this.getPais().equals(castOther.getPais()) ) );
   }
   
}
