package entidades;
import java.util.HashSet;
import java.util.Set;


/**
 * Pais generated by hbm2java
 */

public class Pais  implements java.io.Serializable {


    // Fields    

     private long codigo;
     private Continente continente;
     private String nome;
     private String sigla;
     private String nacionalidade;

    // Constructors

    /** default constructor */
    public Pais() {
    }
    
    /** full constructor */
    public Pais(long codigo, Continente continente, String nome, String sigla, String nacionalidade) {
        this.codigo = codigo;
        this.continente = continente;
        this.nome = nome;
        this.sigla = sigla;
        this.nacionalidade = nacionalidade;
    }
    
    public Pais(Continente continente, String nome, String sigla, String nacionalidade) {
        this.continente = continente;
        this.nome = nome;
        this.sigla = sigla;
        this.nacionalidade = nacionalidade;
    }
   
    // Property accessors

    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }

    public Continente getContinente() {
        return this.continente;
    }
    
    public void setContinente(Continente continente) {
        this.continente = continente;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }
}
