--------------------------------------------------------
--  Arquivo criado - Terça-feira-Outubro-07-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CANAL_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."CANAL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORIA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."CATEGORIA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTINENTE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."CONTINENTE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MARCA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."MARCA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MODELAGEM_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."MODELAGEM_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PADRAO_MEDIDA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."PADRAO_MEDIDA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAIS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."PAIS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TAMANHO_TIPO_GRADE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."TAMANHO_TIPO_GRADE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIPO_GRADE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."TIPO_GRADE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIPO_MEDIDA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RIGHTSIZE"."TIPO_MEDIDA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CANAL
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."CANAL" 
   (  "ID" NUMBER(*,0), 
  "DESCRICAO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."CATEGORIA" 
   (  "ID" NUMBER(*,0), 
  "ICONE" VARCHAR2(500 BYTE), 
  "IMAGEM" VARCHAR2(500 BYTE), 
  "DESCRICAO" VARCHAR2(500 BYTE), 
  "CATEGORIA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTINENTE
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."CONTINENTE" 
   (  "ID" NUMBER(*,0), 
  "NOME" VARCHAR2(100 BYTE), 
  "SIGLA" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MARCA
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."MARCA" 
   (  "ID" NUMBER(*,0), 
  "NOME" VARCHAR2(200 BYTE), 
  "DESCRICAO" VARCHAR2(500 BYTE), 
  "LOGOMARCA" VARCHAR2(500 BYTE), 
  "DATA_CRIACAO" DATE, 
  "GENERO" VARCHAR2(1 BYTE), 
  "IDADE_INICIAL" NUMBER(3,0), 
  "IDADE_FINAL" NUMBER(3,0), 
  "STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MARCA_CANAL
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."MARCA_CANAL" 
   (  "FORMA_ACESSO" VARCHAR2(100 BYTE), 
  "OBSERVACOES" VARCHAR2(500 BYTE), 
  "MARCA_ID" NUMBER(*,0), 
  "CANAL_ID" NUMBER(*,0), 
  "ABRANGENCIA" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODELAGEM
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."MODELAGEM" 
   (  "ID" NUMBER(*,0), 
  "NOME" VARCHAR2(100 BYTE), 
  "STATUS" VARCHAR2(1 BYTE), 
  "GENERO" VARCHAR2(1 BYTE), 
  "DESCRICAO" VARCHAR2(500 BYTE), 
  "ID_INTERNO_INDUSTRIA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODELAGEM_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."MODELAGEM_CATEGORIA" 
   (  "MODELAGEM_ID" NUMBER(*,0), 
  "CATEGORIA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODELAGEM_DADOS_TAMANHO
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" 
   (  "VALOR_MEDIDA_INICIAL" FLOAT(126), 
  "MODELAGEM_ID" NUMBER(*,0), 
  "TAMANHO_TIPO_GRADE_ID" NUMBER(*,0), 
  "PADRAO_MEDIDA_ID" NUMBER(*,0), 
  "TIPO_MEDIDA_ID" NUMBER(*,0), 
  "VALOR_MEDIDA_FINAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODELAGEM_MARCA
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."MODELAGEM_MARCA" 
   (  "MODELAGEM_ID" NUMBER(*,0), 
  "MARCA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PADRAO_MEDIDA
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."PADRAO_MEDIDA" 
   (  "ID" NUMBER(*,0), 
  "DESCRICAO" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAIS
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."PAIS" 
   (  "ID" NUMBER(*,0), 
  "NOME" VARCHAR2(100 BYTE), 
  "SIGLA" VARCHAR2(4 BYTE), 
  "CONTINENTE_ID" NUMBER(*,0), 
  "NACIONALIDADE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAIS_MARCA
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."PAIS_MARCA" 
   (  "MARCA_ID" NUMBER(*,0), 
  "PAIS_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAMANHO_TIPO_GRADE
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."TAMANHO_TIPO_GRADE" 
   (  "ID" NUMBER(*,0), 
  "DESCRICAO" VARCHAR2(500 BYTE), 
  "TIPO_GRADE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_GRADE
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."TIPO_GRADE" 
   (  "ID" NUMBER(*,0), 
  "DESCRICAO" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_MEDIDA
--------------------------------------------------------

  CREATE TABLE "RIGHTSIZE"."TIPO_MEDIDA" 
   (  "ID" NUMBER(*,0), 
  "DESCRICAO" VARCHAR2(500 BYTE), 
  "ABREVIACAO" VARCHAR2(10 BYTE), 
  "NOME" VARCHAR2(200 BYTE), 
  "FIGURA_FORMA_MEDIDA" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into RIGHTSIZE.CANAL
SET DEFINE OFF;
Insert into RIGHTSIZE.CANAL (ID,DESCRICAO) values ('3','Facebook');
Insert into RIGHTSIZE.CANAL (ID,DESCRICAO) values ('6','redetv');
REM INSERTING into RIGHTSIZE.CATEGORIA
SET DEFINE OFF;
Insert into RIGHTSIZE.CATEGORIA (ID,ICONE,IMAGEM,DESCRICAO,CATEGORIA_ID) values ('4','Path For Icone','Path for imagem','Sport',null);
Insert into RIGHTSIZE.CATEGORIA (ID,ICONE,IMAGEM,DESCRICAO,CATEGORIA_ID) values ('5','Path For Icone1','Path for imagem1','Sport1',null);
Insert into RIGHTSIZE.CATEGORIA (ID,ICONE,IMAGEM,DESCRICAO,CATEGORIA_ID) values ('6','Path For Icone1','Path for imagem1','Sport1',null);
Insert into RIGHTSIZE.CATEGORIA (ID,ICONE,IMAGEM,DESCRICAO,CATEGORIA_ID) values ('7','Path For Icone1','Path for imagem1','Sport1','7');
Insert into RIGHTSIZE.CATEGORIA (ID,ICONE,IMAGEM,DESCRICAO,CATEGORIA_ID) values ('8','Path For Icone1','Path for imagem1','Sport1','8');
REM INSERTING into RIGHTSIZE.CONTINENTE
SET DEFINE OFF;
Insert into RIGHTSIZE.CONTINENTE (ID,NOME,SIGLA) values ('12','América Latina','AL');
Insert into RIGHTSIZE.CONTINENTE (ID,NOME,SIGLA) values ('13','Oceania','OC');
Insert into RIGHTSIZE.CONTINENTE (ID,NOME,SIGLA) values ('3','Asia','AS');
REM INSERTING into RIGHTSIZE.MARCA
SET DEFINE OFF;
Insert into RIGHTSIZE.MARCA (ID,NOME,DESCRICAO,LOGOMARCA,DATA_CRIACAO,GENERO,IDADE_INICIAL,IDADE_FINAL,STATUS) values ('1','puma','tenis','puma',to_date('06/10/14','DD/MM/RR'),'M','10','20','Y');
REM INSERTING into RIGHTSIZE.MARCA_CANAL
SET DEFINE OFF;
REM INSERTING into RIGHTSIZE.MODELAGEM
SET DEFINE OFF;
Insert into RIGHTSIZE.MODELAGEM (ID,NOME,STATUS,GENERO,DESCRICAO,ID_INTERNO_INDUSTRIA) values ('1','Model','Y','M','Modelagem','Modelagem Modelo Tal');
REM INSERTING into RIGHTSIZE.MODELAGEM_CATEGORIA
SET DEFINE OFF;
REM INSERTING into RIGHTSIZE.MODELAGEM_DADOS_TAMANHO
SET DEFINE OFF;
REM INSERTING into RIGHTSIZE.MODELAGEM_MARCA
SET DEFINE OFF;
REM INSERTING into RIGHTSIZE.PADRAO_MEDIDA
SET DEFINE OFF;
Insert into RIGHTSIZE.PADRAO_MEDIDA (ID,DESCRICAO) values ('10','PadraoMedida1');
Insert into RIGHTSIZE.PADRAO_MEDIDA (ID,DESCRICAO) values ('11','PadraoMedida3');
REM INSERTING into RIGHTSIZE.PAIS
SET DEFINE OFF;
Insert into RIGHTSIZE.PAIS (ID,NOME,SIGLA,CONTINENTE_ID,NACIONALIDADE) values ('12','Austrália','AUS','12','australiano');
REM INSERTING into RIGHTSIZE.PAIS_MARCA
SET DEFINE OFF;
REM INSERTING into RIGHTSIZE.TAMANHO_TIPO_GRADE
SET DEFINE OFF;
REM INSERTING into RIGHTSIZE.TIPO_GRADE
SET DEFINE OFF;
Insert into RIGHTSIZE.TIPO_GRADE (ID,DESCRICAO) values ('2','Tipo Grade');
REM INSERTING into RIGHTSIZE.TIPO_MEDIDA
SET DEFINE OFF;
Insert into RIGHTSIZE.TIPO_MEDIDA (ID,DESCRICAO,ABREVIACAO,NOME,FIGURA_FORMA_MEDIDA) values ('1','TMEDIDADESC','TMDC2','TipoMedida3','Patch3');
--------------------------------------------------------
--  DDL for Index CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."CATEGORIA_PK" ON "RIGHTSIZE"."CATEGORIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MARCA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."MARCA_PK" ON "RIGHTSIZE"."MARCA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_GRADE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."TIPO_GRADE_PK" ON "RIGHTSIZE"."TIPO_GRADE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAMANHO_TIPO_GRADE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."TAMANHO_TIPO_GRADE_PK" ON "RIGHTSIZE"."TAMANHO_TIPO_GRADE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_MEDIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."TIPO_MEDIDA_PK" ON "RIGHTSIZE"."TIPO_MEDIDA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MODELAGEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."MODELAGEM_PK" ON "RIGHTSIZE"."MODELAGEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PADRAO_MEDIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."PADRAO_MEDIDA_PK" ON "RIGHTSIZE"."PADRAO_MEDIDA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."PAIS_PK" ON "RIGHTSIZE"."PAIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CANAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."CANAL_PK" ON "RIGHTSIZE"."CANAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTINENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RIGHTSIZE"."CONTINENTE_PK" ON "RIGHTSIZE"."CONTINENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MODELAGEM_MARCA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MODELAGEM_MARCA" MODIFY ("MARCA_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_MARCA" MODIFY ("MODELAGEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANAL
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."CANAL" ADD CONSTRAINT "CANAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."CANAL" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."CANAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTINENTE
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."CONTINENTE" ADD CONSTRAINT "CONTINENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."CONTINENTE" MODIFY ("SIGLA" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."CONTINENTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MARCA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MARCA" ADD CONSTRAINT "MARCA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."MARCA" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MARCA" MODIFY ("IDADE_FINAL" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MARCA" MODIFY ("IDADE_INICIAL" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MARCA" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MARCA" MODIFY ("DATA_CRIACAO" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MARCA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MARCA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODELAGEM_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MODELAGEM_CATEGORIA" MODIFY ("CATEGORIA_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_CATEGORIA" MODIFY ("MODELAGEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODELAGEM
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MODELAGEM" ADD CONSTRAINT "MODELAGEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."MODELAGEM" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MODELAGEM" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MODELAGEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PADRAO_MEDIDA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."PADRAO_MEDIDA" ADD CONSTRAINT "PADRAO_MEDIDA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."PADRAO_MEDIDA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_GRADE
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."TIPO_GRADE" ADD CONSTRAINT "TIPO_GRADE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."TIPO_GRADE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODELAGEM_DADOS_TAMANHO
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" MODIFY ("TIPO_MEDIDA_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" MODIFY ("PADRAO_MEDIDA_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" MODIFY ("TAMANHO_TIPO_GRADE_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" MODIFY ("MODELAGEM_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" MODIFY ("VALOR_MEDIDA_INICIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_MEDIDA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."TIPO_MEDIDA" ADD CONSTRAINT "TIPO_MEDIDA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."TIPO_MEDIDA" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."TIPO_MEDIDA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAMANHO_TIPO_GRADE
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."TAMANHO_TIPO_GRADE" ADD CONSTRAINT "TAMANHO_TIPO_GRADE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."TAMANHO_TIPO_GRADE" MODIFY ("TIPO_GRADE_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."TAMANHO_TIPO_GRADE" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."TAMANHO_TIPO_GRADE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAIS_MARCA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."PAIS_MARCA" MODIFY ("PAIS_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."PAIS_MARCA" MODIFY ("MARCA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."CATEGORIA" ADD CONSTRAINT "CATEGORIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."CATEGORIA" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."CATEGORIA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAIS
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."PAIS" ADD CONSTRAINT "PAIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RIGHTSIZE"."PAIS" MODIFY ("NACIONALIDADE" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."PAIS" MODIFY ("CONTINENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."PAIS" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."PAIS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MARCA_CANAL
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MARCA_CANAL" MODIFY ("CANAL_ID" NOT NULL ENABLE);
  ALTER TABLE "RIGHTSIZE"."MARCA_CANAL" MODIFY ("MARCA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."CATEGORIA" ADD CONSTRAINT "CATEGORIA_CATEGORIA_FK" FOREIGN KEY ("CATEGORIA_ID")
    REFERENCES "RIGHTSIZE"."CATEGORIA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MARCA_CANAL
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MARCA_CANAL" ADD CONSTRAINT "MARCA_CANAL_CANAL_FK" FOREIGN KEY ("CANAL_ID")
    REFERENCES "RIGHTSIZE"."CANAL" ("ID") ENABLE;
  ALTER TABLE "RIGHTSIZE"."MARCA_CANAL" ADD CONSTRAINT "MARCA_CANAL_MARCA_FK" FOREIGN KEY ("MARCA_ID")
    REFERENCES "RIGHTSIZE"."MARCA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODELAGEM_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MODELAGEM_CATEGORIA" ADD CONSTRAINT "CATEGORIA_FK" FOREIGN KEY ("CATEGORIA_ID")
    REFERENCES "RIGHTSIZE"."CATEGORIA" ("ID") ENABLE;
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_CATEGORIA" ADD CONSTRAINT "MODELAGEM_TABLE_FK" FOREIGN KEY ("MODELAGEM_ID")
    REFERENCES "RIGHTSIZE"."MODELAGEM" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODELAGEM_DADOS_TAMANHO
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" ADD CONSTRAINT "MODELAGEM_FK" FOREIGN KEY ("MODELAGEM_ID")
    REFERENCES "RIGHTSIZE"."MODELAGEM" ("ID") ENABLE;
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" ADD CONSTRAINT "PADRAO_MEDIDA_FK" FOREIGN KEY ("PADRAO_MEDIDA_ID")
    REFERENCES "RIGHTSIZE"."PADRAO_MEDIDA" ("ID") ENABLE;
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" ADD CONSTRAINT "TAMANHO_TIPO_GRADE_FK" FOREIGN KEY ("TAMANHO_TIPO_GRADE_ID")
    REFERENCES "RIGHTSIZE"."TAMANHO_TIPO_GRADE" ("ID") ENABLE;
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_DADOS_TAMANHO" ADD CONSTRAINT "TIPO_MEDIDA_FK" FOREIGN KEY ("TIPO_MEDIDA_ID")
    REFERENCES "RIGHTSIZE"."TIPO_MEDIDA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODELAGEM_MARCA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."MODELAGEM_MARCA" ADD CONSTRAINT "MODELAGEM_MARCA_MARCA_FK" FOREIGN KEY ("MARCA_ID")
    REFERENCES "RIGHTSIZE"."MARCA" ("ID") ENABLE;
  ALTER TABLE "RIGHTSIZE"."MODELAGEM_MARCA" ADD CONSTRAINT "MODELAGEM_MARCA_MODELAGEM_FK" FOREIGN KEY ("MODELAGEM_ID")
    REFERENCES "RIGHTSIZE"."MODELAGEM" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAIS
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."PAIS" ADD CONSTRAINT "PAIS_CONTINENTE_FK" FOREIGN KEY ("CONTINENTE_ID")
    REFERENCES "RIGHTSIZE"."CONTINENTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAIS_MARCA
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."PAIS_MARCA" ADD CONSTRAINT "PAIS_MARCA_MARCA_FK" FOREIGN KEY ("MARCA_ID")
    REFERENCES "RIGHTSIZE"."MARCA" ("ID") ENABLE;
  ALTER TABLE "RIGHTSIZE"."PAIS_MARCA" ADD CONSTRAINT "PAIS_MARCA_PAIS_FK" FOREIGN KEY ("PAIS_ID")
    REFERENCES "RIGHTSIZE"."PAIS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAMANHO_TIPO_GRADE
--------------------------------------------------------

  ALTER TABLE "RIGHTSIZE"."TAMANHO_TIPO_GRADE" ADD CONSTRAINT "TIPO_GRADE_FK" FOREIGN KEY ("TIPO_GRADE_ID")
    REFERENCES "RIGHTSIZE"."TIPO_GRADE" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CANAL_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."CANAL_ID_TRG" BEFORE
  INSERT ON canal FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := canal_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."CANAL_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORIA_IDO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."CATEGORIA_IDO_TRG" BEFORE
  INSERT ON categoria FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := categoria_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."CATEGORIA_IDO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTINENTE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."CONTINENTE_ID_TRG" BEFORE
  INSERT ON continente FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := continente_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."CONTINENTE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MARCA_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."MARCA_ID_TRG" BEFORE
  INSERT ON marca FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := marca_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."MARCA_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MODELAGEM_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."MODELAGEM_ID_TRG" BEFORE
  INSERT ON modelagem FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := modelagem_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."MODELAGEM_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PADRAO_MEDIDA_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."PADRAO_MEDIDA_ID_TRG" BEFORE
  INSERT ON padrao_medida FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := padrao_medida_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."PADRAO_MEDIDA_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PAIS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."PAIS_ID_TRG" BEFORE
  INSERT ON pais FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := pais_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."PAIS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TAMANHO_TIPO_GRADE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."TAMANHO_TIPO_GRADE_ID_TRG" BEFORE
  INSERT ON tamanho_tipo_grade FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := tamanho_tipo_grade_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."TAMANHO_TIPO_GRADE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIPO_GRADE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."TIPO_GRADE_ID_TRG" BEFORE
  INSERT ON tipo_grade FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := tipo_grade_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."TIPO_GRADE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIPO_MEDIDA_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RIGHTSIZE"."TIPO_MEDIDA_ID_TRG" BEFORE
  INSERT ON tipo_medida FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN :NEW.id := tipo_medida_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "RIGHTSIZE"."TIPO_MEDIDA_ID_TRG" ENABLE;
