package entidades;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;


/**
 * Categoria generated by hbm2java
 */

public class Categoria{


    // Fields    

     private BigDecimal codigo;
     private Categoria categoria;
     private String icone;
     private String imagem;
     private String descricao;


    // Constructors

    /** default constructor */
    public Categoria() {
    }
    
    /** full constructor */
    public Categoria(BigDecimal codigo, Categoria categoria, String icone, String imagem, String descricao) {
        this.codigo = codigo;
        this.categoria = categoria;
        this.icone = icone;
        this.imagem = imagem;
        this.descricao = descricao;
    }
    
   
    // Property accessors

    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }

    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public String getIcone() {
        return this.icone;
    }
    
    public void setIcone(String icone) {
        this.icone = icone;
    }

    public String getImagem() {
        return this.imagem;
    }
    
    public void setImagem(String imagem) {
        this.imagem = imagem;
    }

    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }


}
