package entidades;




/**
 * MarcaCanal generated by hbm2java
 */

public class MarcaCanal  implements java.io.Serializable {


    // Fields    

     private MarcaCanalId id;


    // Constructors

    /** default constructor */
    public MarcaCanal() {
    }

    
    /** full constructor */
    public MarcaCanal(MarcaCanalId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public MarcaCanalId getId() {
        return this.id;
    }
    
    public void setId(MarcaCanalId id) {
        this.id = id;
    }
   








}
