package entidades;


/**
 * ModelagemCategoria generated by hbm2java
 */

public class ModelagemCategoria  implements java.io.Serializable {


    // Fields    

     private ModelagemCategoriaId id;


    // Constructors

    /** default constructor */
    public ModelagemCategoria() {
    }

    
    /** full constructor */
    public ModelagemCategoria(ModelagemCategoriaId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public ModelagemCategoriaId getId() {
        return this.id;
    }
    
    public void setId(ModelagemCategoriaId id) {
        this.id = id;
    }
   








}
