package entidades;


/**
 * ModelagemDadosTamanho generated by hbm2java
 */

public class ModelagemDadosTamanho  implements java.io.Serializable {


    // Fields    

     private ModelagemDadosTamanhoId id;


    // Constructors

    /** default constructor */
    public ModelagemDadosTamanho() {
    }

    
    /** full constructor */
    public ModelagemDadosTamanho(ModelagemDadosTamanhoId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public ModelagemDadosTamanhoId getId() {
        return this.id;
    }
    
    public void setId(ModelagemDadosTamanhoId id) {
        this.id = id;
    }
   








}
