package entidades;


/**
 * ModelagemMarcaId generated by hbm2java
 */

public class ModelagemMarcaId  implements java.io.Serializable {


    // Fields    

     private Modelagem modelagem;
     private Marca marca;


    // Constructors

    /** default constructor */
    public ModelagemMarcaId() {
    }

    
    /** full constructor */
    public ModelagemMarcaId(Modelagem modelagem, Marca marca) {
        this.modelagem = modelagem;
        this.marca = marca;
    }
    

   
    // Property accessors

    public Modelagem getModelagem() {
        return this.modelagem;
    }
    
    public void setModelagem(Modelagem modelagem) {
        this.modelagem = modelagem;
    }

    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelagemMarcaId) ) return false;
		 ModelagemMarcaId castOther = ( ModelagemMarcaId ) other; 
         
		 return ( (this.getModelagem()==castOther.getModelagem()) || ( this.getModelagem()!=null && castOther.getModelagem()!=null && this.getModelagem().equals(castOther.getModelagem()) ) )
 && ( (this.getMarca()==castOther.getMarca()) || ( this.getMarca()!=null && castOther.getMarca()!=null && this.getMarca().equals(castOther.getMarca()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getModelagem() == null ? 0 : this.getModelagem().hashCode() );
         result = 37 * result + ( getMarca() == null ? 0 : this.getMarca().hashCode() );
         return result;
   }   





}
