package entidades;

/**
 * ModelagemCategoriaId generated by hbm2java
 */

public class ModelagemCategoriaId  implements java.io.Serializable {


    // Fields    

     private Modelagem modelagem;
     private Categoria categoria;


    // Constructors

    /** default constructor */
    public ModelagemCategoriaId() {
    }

    
    /** full constructor */
    public ModelagemCategoriaId(Modelagem modelagem, Categoria categoria) {
        this.modelagem = modelagem;
        this.categoria = categoria;
    }
    

   
    // Property accessors

    public Modelagem getModelagem() {
        return this.modelagem;
    }
    
    public void setModelagem(Modelagem modelagem) {
        this.modelagem = modelagem;
    }

    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelagemCategoriaId) ) return false;
		 ModelagemCategoriaId castOther = ( ModelagemCategoriaId ) other; 
         
		 return ( (this.getModelagem()==castOther.getModelagem()) || ( this.getModelagem()!=null && castOther.getModelagem()!=null && this.getModelagem().equals(castOther.getModelagem()) ) )
 && ( (this.getCategoria()==castOther.getCategoria()) || ( this.getCategoria()!=null && castOther.getCategoria()!=null && this.getCategoria().equals(castOther.getCategoria()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getModelagem() == null ? 0 : this.getModelagem().hashCode() );
         result = 37 * result + ( getCategoria() == null ? 0 : this.getCategoria().hashCode() );
         return result;
   }   





}
