package entidades;


/**
 * ModelagemMarca generated by hbm2java
 */

public class ModelagemMarca  implements java.io.Serializable {


    // Fields    

     private ModelagemMarcaId id;


    // Constructors

    /** default constructor */
    public ModelagemMarca() {
    }

    
    /** full constructor */
    public ModelagemMarca(ModelagemMarcaId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public ModelagemMarcaId getId() {
        return this.id;
    }
    
    public void setId(ModelagemMarcaId id) {
        this.id = id;
    }
   








}
