package entidades;


/**
 * PaisMarcaId generated by hbm2java
 */

public class PaisMarcaId  implements java.io.Serializable {


    // Fields    

     private Marca marca;
     private Pais pais;


    // Constructors

    /** default constructor */
    public PaisMarcaId() {
    }

    
    /** full constructor */
    public PaisMarcaId(Marca marca, Pais pais) {
        this.marca = marca;
        this.pais = pais;
    }
    

   
    // Property accessors

    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaisMarcaId) ) return false;
		 PaisMarcaId castOther = ( PaisMarcaId ) other; 
         
		 return ( (this.getMarca()==castOther.getMarca()) || ( this.getMarca()!=null && castOther.getMarca()!=null && this.getMarca().equals(castOther.getMarca()) ) )
 && ( (this.getPais()==castOther.getPais()) || ( this.getPais()!=null && castOther.getPais()!=null && this.getPais().equals(castOther.getPais()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMarca() == null ? 0 : this.getMarca().hashCode() );
         result = 37 * result + ( getPais() == null ? 0 : this.getPais().hashCode() );
         return result;
   }   





}
