package entidades;


/**
 * PaisMarca generated by hbm2java
 */

public class PaisMarca{


    // Fields    

     private PaisMarcaId id;


    // Constructors

    /** default constructor */
    public PaisMarca() {
    }

    
    /** full constructor */
    public PaisMarca(PaisMarcaId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public PaisMarcaId getId() {
        return this.id;
    }
    
    public void setId(PaisMarcaId id) {
        this.id = id;
    }
   








}
